### ISSUE TITLE
Change map default date format listed incorrectly

### ISSUE THREAD

**Issue by bullocke** [ceholden/yatsm#55]
In the change map script, the date format is listed in the help to default to %Y%j:
https://github.com/ceholden/yatsm/blob/master/yatsm/cli/changemap.py#L40
 
....but not specifying it differently gives the following error: 
"Error: Invalid value for "start_date": Cannot parse 1984001 to date with format %Y-%m-%d."

I believe it is because in the option code line 90 it is listed as defaulting to "default='%Y-%m-%d'," 
https://github.com/ceholden/yatsm/blob/master/yatsm/cli/options.py#L90. 

Any user can probably figure this out by listing the format they want, but this might want to fixed in a future release.

**Comment by ceholden** [comment]
I don't think this is an error or I'm misunderstanding your problem.

There are two separate date formatting options:
- `--date <format>`
    + input argument date strings
    + default %Y-%m-%d
- `--out_date <format>`
    + output date format for the maps
    + default %Y%j

The error message you describe is actually 100% correct -- the input `start_date` is not parsable as a date with `%Y-%m-%d` because it lacks the dashes and you're passing something that looks more like a `%Y%j`. If you change the usage to include `--date %Y%j`, it works:

``` 
> yatsm -v changemap --root ../landsat_stack/p022r049/images/ first 2000001 2001001 test.gtif
Usage: yatsm changemap [OPTIONS] <map_type> <start_date> <end_date> <output>

Error: Invalid value for "start_date": Cannot parse 20000101 to date with format %Y-%m-%d
```
versus
```
> yatsm -v changemap --root ../landsat_stack/p022r049/images/ --date %Y%j first 2000001 2001001 test.gtif
```
which works.

If you look at the [parsing for the date argument](https://github.com/ceholden/yatsm/blob/master/yatsm/cli/options.py#L51) you'll see that it is connected to the `date_frmt` or `--date` option. This date format option is parsed "eagerly", meaning that it is parsed before the `date` argument is parsed.

The `--out_date` works for the map products. By default, the output format is %Y%j:
```
> yatsm -v changemap --root ../landsat_stack/p022r049/images/ --date %Y%j first 2005001 2006001 test.gtif
> gdalinfo -mm test.gtif | grep "Min/Max"
    Computed Min/Max=2005002.000,2005338.000
```
versus
```
> yatsm -v changemap --root ../landsat_stack/p022r049/images/ --date %Y%j --out_date %Y%m%d first 2005001 2006001 test.gtif
> gdalinfo -mm test.gtif | grep "Min/Max"
    Computed Min/Max=20050102.000,20051204.000
```

**Comment by ceholden** [comment]
If you suggest some change to the description text that makes more sense, I'd be happy to make the change. Something like "Input date format" instead of just "Date format"? I'd like to keep the current text for the options, so as to remain backward compatible, but we can change the descriptions.

**Comment by bullocke** [comment]
Oh I see, this makes perfect sense. Sorry about that! I guess I was not paying close enough attention to the options. Maybe adding 'Input' to the description like you said would make it a little more clear?

**Comment by ceholden** [comment]
No problem -- sorry for the confusion! I've modified the option description to be "Input date format" as discussed.

Thanks for the clarification issue. Please keep them coming. I doubt all the CLI are intuitive given that there's currently no good documentation or user guide and all of the code has been bouncing around in mostly just my head.
